Adding db
StephanYorchenko/such-a-lovely-js pull request #18
Opened 2021-05-19 19:21 UTC by lololozhkin

DB calls added instead of fake repositories

2021-05-20 03:12 UTC, StephanYorchenko requested changes
1) Попробуй всё таки оставить запуск проекта и корня, перенеся докерфайлы в корень и закинув всё лишнее из корня в докеригнор

2021-05-20 03:12 UTC, StephanYorchenko commented on src/.dockerignore
> +/node_modules/
Мб чтобы не мучиться с переносом тестов, будем запускать докер из корня, но докинем все ридми в докеригнор? Так вроде норм должно получится

2021-05-20 03:12 UTC, StephanYorchenko commented on src/core/useCases/getSurveyData.js
> +	static async execute(params) {
Зачем пробел перед {?

2021-05-20 03:12 UTC, StephanYorchenko commented on src/infrastructure/repositories/userRepository.js
> +		const user = await db.User.findByPk(userID);
А зачем тебе юзера в константу выводить? Сразу его возвращать ведь можно

2021-05-20 04:40 UTC, lololozhkin commented on src/core/useCases/getSurveyData.js
> +	static async execute(params) {
Это выглядит симпатичнее и привычнее. Вроде тут стайл почти как в плюсах по поводу скобок а там принято оставлять пробел

2021-05-20 04:41 UTC, lololozhkin commented on src/infrastructure/repositories/userRepository.js
> +		const user = await db.User.findByPk(userID);
Это чисто по приколу. Почему нет. Тут даже конст а не лет или вар ведь юзер не меняется 🤣🤣🤣

2021-05-20 04:43 UTC, lololozhkin commented on src/.dockerignore
> +/node_modules/
Нет. Тут по-хорошему все же держать пэкедж в срс. Потому что это другой слой. Корень по сути это какая-то деплойная штука, а срс это приложение, и зависимости нужны именно ему, а не всему проекту. А ci/CD скорее всего можно настроить так, чтобы он трогал только срс. Или вообще сам делал make. Можно даже написать команду make test чтобы в ci ее запускать.

2021-05-20 04:55 UTC, StephanYorchenko commented on src/.dockerignore
> +/node_modules/
Не спорю, можно

2021-05-20 04:56 UTC, lololozhkin commented on src/.dockerignore
> +/node_modules/
Make test я сделаю!! А ci я не настраивал :( проконсультируй 🥺

2021-05-28 17:50 UTC, StephanYorchenko approved these changes, later dismissed
Вроде ок

2021-05-28 18:23 UTC, StephanYorchenko approved these changes
Надеюсь что ок

2021-05-28 18:23 UTC, merged